project:
  type: website
  title: Can.Do.So

website:
  title: "Can.Do.So"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: demoR/demoR.qmd
        text: R Tutorials

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


