project:
  type: website

website:
  title: "reddylee.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: demoR/demoR.qmd
        text: R Tutorials

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


